[package]
name = "msr"
description = "Industrial automation library"
version = "0.1.0"
authors = ["Markus Kohlhase <markus.kohlhase@slowtec.de>"]
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["automation", "control", "plc", "msr"]
homepage = "https://github.com/slowtec/msr"
repository = "https://github.com/slowtec/msr"

[dependencies]
serde_derive = { version = "1.0", optional = true }
serde = { version = "1.0", optional = true }

[features]
default = ["serde_support"]
serde_support = ["serde_derive", "serde"]

[badges]
travis-ci = { repository = "slowtec/msr" }
